# Generated by Django 5.2.12 on 2026-03-23 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=1024)),
                ('contenu_texte', models.TextField()),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut_analyse', models.CharField(default='EN_ATTENTE', max_length=50)),
            ],
            options={
                'db_table': 'DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='SourceComparaison',
            fields=[
                ('id_source', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_source', models.CharField(max_length=50)),
                ('titre_source', models.CharField(max_length=255)),
                ('auteur_source', models.CharField(blank=True, default='', max_length=255)),
                ('url_source', models.URLField(max_length=1024)),
                ('contenu_source', models.TextField()),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'SOURCE_COMPARAISON',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(default='USER', max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UTILISATEUR',
            },
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id_analyse', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_analyse', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_global', models.FloatField()),
                ('nombre_sources_trouvees', models.IntegerField(default=0)),
                ('etat_analyse', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='accounts.document')),
            ],
            options={
                'db_table': 'ANALYSE',
            },
        ),
        migrations.CreateModel(
            name='ResultatSimilarite',
            fields=[
                ('id_resultat', models.BigAutoField(primary_key=True, serialize=False)),
                ('score_similarite', models.FloatField()),
                ('pourcentage_correspondance', models.FloatField()),
                ('id_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.analyse')),
                ('id_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.sourcecomparaison')),
            ],
            options={
                'db_table': 'RESULTAT_SIMILARITE',
            },
        ),
        migrations.CreateModel(
            name='PassagePlagie',
            fields=[
                ('id_passage', models.BigAutoField(primary_key=True, serialize=False)),
                ('texte_document', models.TextField()),
                ('texte_source', models.TextField()),
                ('position_debut', models.IntegerField()),
                ('position_fin', models.IntegerField()),
                ('taux_similarite_passage', models.FloatField()),
                ('id_resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='accounts.resultatsimilarite')),
            ],
            options={
                'db_table': 'PASSAGE_PLAGIE',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.utilisateur'),
        ),
    ]
