# Generated by Django 5.2.12 on 2026-03-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_django_users_to_utilisateurs(apps, schema_editor):
    """Associe chaque User à un Utilisateur distinct (évite l’historique partagé par e-mail)."""
    User = apps.get_model("auth", "User")
    Utilisateur = apps.get_model("accounts", "Utilisateur")
    for user in User.objects.all().order_by("id"):
        if Utilisateur.objects.filter(django_user_id=user.id).exists():
            continue
        email = (user.email or "").strip().lower()
        if not email:
            username = (user.username or "user").strip().lower().replace(" ", "_")
            email = f"{username}@plagguard.local"
        email = email[:254]
        cand = (
            Utilisateur.objects.filter(django_user__isnull=True, email__iexact=email)
            .exclude(email__startswith="guest_")
            .first()
        )
        if cand:
            cand.django_user_id = user.id
            cand.save(update_fields=["django_user_id"])
            continue
        nom = (user.last_name or "").strip() or "Inconnu"
        prenom = (user.first_name or "").strip() or (user.username or "Utilisateur")
        role = "ADMIN" if user.is_superuser else ("STAFF" if user.is_staff else "USER")
        final_email = email
        if Utilisateur.objects.filter(email__iexact=final_email).exists():
            final_email = f"compte_{user.id}@users.plagguard.local"[:254]
        Utilisateur.objects.create(
            django_user_id=user.id,
            email=final_email,
            nom=nom[:150],
            prenom=prenom[:150],
            mot_de_passe=user.password,
            role=role,
        )


def unlink_django_users(apps, schema_editor):
    Utilisateur = apps.get_model("accounts", "Utilisateur")
    Utilisateur.objects.all().update(django_user_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document_sourcecomparaison_utilisateur_analyse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plagguard_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RunPython(link_django_users_to_utilisateurs, unlink_django_users),
    ]
