# Generated by Django 5.2.12 on 2026-03-25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_django_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementWaafi',
            fields=[
                ('id_abonnement', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Forfait Gratuit'), ('PRO', 'Pro'), ('PROPLUS', 'Pro+')], default='FREE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('ECHOUER', 'Échoué'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('reference_waafi', models.CharField(max_length=64, unique=True)),
                ('transaction_id_waafi', models.CharField(blank=True, default='', max_length=64)),
                ('raw_status', models.CharField(blank=True, default='', max_length=64)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'ABONNEMENT_WAAFIPAY',
            },
        ),
    ]

