# Generated by Django 5.2.12 on 2026-03-26 09:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_abonnement_waafipay'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='abonnementwaafi',
            name='reference_waafi',
            field=models.CharField(default=accounts.models.AbonnementWaafi._generate_reference_waafi, max_length=64, unique=True),
        ),
    ]
