"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _parse_dotenv_file(path: Path) -> dict[str, str]:
    """Lit KEY=VALUE depuis .env (sans dépendre de python-dotenv). utf-8-sig = BOM Windows."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    try:
        text = path.read_text(encoding="utf-8-sig")
    except OSError:
        return out
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip().strip('"').strip("'")
        if key:
            out[key] = val
    return out


# Charge .env à la racine du projet (clé Tavily, etc.)
# override=True : une variable Windows vide ne bloque plus la valeur du fichier .env
_ENV_PATH = BASE_DIR / ".env"
try:
    from dotenv import load_dotenv

    load_dotenv(_ENV_PATH, override=True)
except ImportError:
    pass

# Fallback si dotenv n'est pas installé ou si la clé est encore vide (ex. env système vide)
_parsed = _parse_dotenv_file(_ENV_PATH)
if not (os.environ.get("TAVILY_API_KEY") or "").strip() and _parsed.get("TAVILY_API_KEY"):
    os.environ["TAVILY_API_KEY"] = _parsed["TAVILY_API_KEY"].strip()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)5&*cvd%k4tdo&3(^bc%id78_kf9u0=+85)$8aeb146wd%1@%6'

# En local : True par défaut (les fichiers dans static/ sont servis par runserver).
# Pour simuler la prod / ngrok : définir DJANGO_DEBUG=0 dans l'environnement.
# Alternative avec DEBUG=False : py manage.py runserver --insecure
DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes", "on")

# ngrok utilise un sous-domaine aléatoire => on accepte les suffixes principaux
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.ngrok-free.app',
    '.ngrok-free.dev',
    '.ngrok.io',
    '.ngrok.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.admin_dashboard_context',
                'accounts.context_processors.device_context',
                'accounts.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'plagiat',
        'USER': 'postgres',
        'PASSWORD': 'admin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Auth
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:accueil'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Derrière un proxy (ngrok) : s'assurer que Django voit le bon schéma HTTPS
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF côté formulaires : autoriser les origins HTTPS ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://rosalba-exstipulate-dismayedly.ngrok-free.dev',
    'https://*.ngrok.io',
    'https://*.ngrok.app',
]

# E-mail (vérification de compte) - SMTP Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "ayoubatteyeh0@gmail.com"
EMAIL_HOST_PASSWORD = "jzqwbujinupmrfic"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# URL publique du site (sans slash final) pour les liens dans les e-mails.
# Indispensable si vous vous inscrivez en localhost mais ouvrez le mail sur un autre appareil,
# ou derrière ngrok / un nom de domaine : ex. https://abc123.ngrok-free.app
SITE_URL = (os.environ.get("SITE_URL", "") or _parsed.get("SITE_URL", "")).strip().rstrip("/")

# Tavily Search API — https://tavily.com/ — définir dans .env : TAVILY_API_KEY=...
TAVILY_API_KEY = (os.environ.get("TAVILY_API_KEY") or "").strip() or _parsed.get("TAVILY_API_KEY", "").strip()

# Sapling AI detector (pour détecteur IA / plagiat) — définir dans .env : SAPLING_API_KEY=...
SAPLING_API_KEY = (os.environ.get("SAPLING_API_KEY") or "").strip() or _parsed.get("SAPLING_API_KEY", "").strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
